### PR TITLE
Adjustments to syntax highlighting

### PR DESCRIPTION
**Pull request by essmahr**
1. Modifies the prismJS theme from the default Monokai. I just picked one I liked from [here](https://github.com/PrismJS/prism-themes). The main difference is that inline `<code>` spans are light instead of dark, and the font-size is bumped down.

### Before
image

### After
image

2. Added support for line highlighting in code blocks. Adding `// highlight-start` and `// highlight-end` comments to code blocks results in the following:

image

CC @craigmdennis

### CODE REVIEW

**Comment by craigmdennis** [comment]
Have you checked light and dark mode?

**Comment by essmahr** [comment]
Yep, dark mode:

(inline code blocks pop a little more here, whereas before they popped a little more in light mode)

image

**Comment by buzinas** [comment]
I use "One Dark Pro" – I think there's one available for prism: https://github.com/AGMStudio/prism-theme-one-dark

image

image

**Review by bartgryszko — COMMENTED** [review]
Changes LGTM, but I'm missing context why are we changing this ;)

**Comment by essmahr** [comment]
@bartgryszko I guess there is not much context -- I found the existing theme to have too big a font-size, and wanted to support line highlighting for an upcoming blog post.

**Pull request merged**
