### PR TITLE
Add robots.txt and disallow crawling .json files

### LINKED ISSUE #91: Google Crawl issue / JSON
@nickpersico found an important issue regarding Google Crawl stats regarding our domain where they're spending too high a % crawling our product/eng blog here -- in particular some JSON. (In Slack I shared a Loom with more details)

What is this JSON?
How do we turn it off?

@closeio/frontend 

Screen Shot 2022-08-24 at 3 59 46 PM

### PR DESCRIPTION
**Pull request by buzinas**
After merging this, Nick (or whoever has access to Google Search Console) should [force an update](https://developers.google.com/search/docs/advanced/robots/submit-updated-robots-txt#refresh-googles-robots.txt-cache), so Google will auto-block all JSON files from now on.

Closes #91

### CODE REVIEW

**Comment by philfreo** [comment]
Do you know what the JSON is to begin with, and how to stop it from being served? (Not just crawled)

Random thought: maybe it's related to the Lever integration?

**Comment by buzinas** [comment]
> Do you know what the JSON is to begin with

Yes.

>  how to stop it from being served? (Not just crawled)

We can't do that. That's how Gatsby work. The pages are pre-rendered on build time in HTML and JSON files. When you first open the page, the HTML is rendered, but then it preloads all visible links automatically (this is what `page-data.json` is about). Whenever you visit a page, it's routed only on the client (there is no page redirect) and Gatsby uses the data returned from this JSON to actually render the page.

If you open the network tab and check the responses you'll get what it's about.

I've used Gatsby a lot in the past, and JSON files being crawled is pretty normal (although they are not considered for search results). That said, if it's a concern for our main blog/website, this is obviously much more important than having good crawling for our engineering blog.

**Review by philfreo — APPROVED** [review]
Thanks!

**Comment by buzinas** [comment]
I assume the main reason for our engineering blog being crawled so many more times than the other websites is just because it has many less pages and it's insanely faster.

Google Bot has a budget when crawling a domain, so it'll spend only the amount of time it "can" to crawls all pages. The more pages you have, the more likely it won't have time to crawl all of them. The longer it takes to crawl, the more likely it won't crawl all. So since we have just a few blog posts and all of them loads ultra fast, it's OK to assume that Google will crawl more making.close.com pages than others.

The link below has some info about this (and it links to a very interesting deeper research as well):
https://www.botify.com/blog/do-slow-page-load-times-negatively-impact-how-google-crawls-your-site

**Pull request merged**
